Add withChecks step
jenkinsci/checks-api-plugin pull request #49
Opened 2020-11-29 12:36 UTC by XiongKezhi

Linked https://github.com/jenkinsci/checks-api-plugin/issues/45

- [x] Add the name for the closure

- [ ] Figuring the way to update the checks (no ideas yet...)

- [ ] Testing

cc @mrginglymus @jglick

2020-11-29 12:39 UTC, XiongKezhi commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +    public WithChecksStep(final String name) {
Is it possible to take more than one args? cause I saw code like https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java#L702

2020-11-29 14:40 UTC, mrginglymus commented
With the usual caveat of 
![image](https://user-images.githubusercontent.com/390569/100544822-56cd4e00-3250-11eb-8dc4-a17c18ac1afb.png)

I had a brief play with this myself and got distracted with also doing the update bits too* - I couldn't see an easy way to do it without changing the API of `ChecksPublisher` to look something like:

```java
public abstract class ChecksPublisher {

    private final Job<?, ?> job;

    public ChecksPublisher(Job<?, ?> job) {
        this.job = job;
    }

    protected abstract void doPublish(ChecksDetails details)  // replaces existing `publish`

    public final void publish(ChecksDetails details) {
        doPublish(details);
        details.getName().ifPresent(name -> job.addOrReplaceAction(new ChecksInfo(name, details.getConsclusion()));
    }

    public ChecksConclusion getConclusion(String checksName) {
        return job.getActions(ChecksInfo.class)
                .stream()
                .filter(a -> a.getName().equals(checksName))
                .findFirst()
                .map(ChecksInfo::getConclusion)
                .orElse(ChecksConclusion.None);
    }
}
```
ie, `ChecksInfo` was an `InvisibleAction`, and there was a separate `WithChecksContext` that stored the current name.

The `WithChecksStep` then implements a `BodyExecutionCallback` that looks something like:

```java
private static final class Callback extends BodyExecutionCallback {
    private static final long serialVersionUID = 1L;

    private ChecksPublisher getPublisher(StepContext context) throws IOException, InterruptedException {
        return ChecksPublisherFactory.fromRun(context.get(Run.class), context.get(TaskListener.class));
    }

    private WithCheckContext getCheckContext(StepContext context) throws IOException, InterruptedException {
        return context.get(WithCheckContext.class);
    }

    private ChecksDetails getDetails(WithCheckContext context, ChecksConclusion conclusion) {
        return new ChecksDetails.ChecksDetailsBuilder()
                .withName(context.getName())
                .withConclusion(conclusion)
                .withStatus(ChecksStatus.COMPLETED)
                .build();
    }

    @Override
    public void onStart(StepContext context) {
        try {
            ChecksDetails details = new ChecksDetails.ChecksDetailsBuilder()
                    .withName(getCheckContext(context).getName())
                    .withStatus(ChecksStatus.IN_PROGRESS)
                    .build();
            getPublisher(context).publish(details);
        } catch (Exception e) {
            context.onFailure(e);
        }
    }

    @Override
    public void onSuccess(StepContext context, Object result) {
        try {
            WithCheckContext checkContext = getCheckContext(context);
            ChecksPublisher publisher = getPublisher(context);
            if (publisher.getConclusion(checkContext.getName()) == ChecksConclusion.NONE) {
                publisher.publish(getDetails(checkContext, ChecksConclusion.SUCCESS));
                context.onSuccess(null);
            }
        } catch (Exception e) {
            context.onFailure(e);
        }
    }

    @Override
    public void onFailure(StepContext context, Throwable t) {
        try {
            WithCheckContext checkContext = getCheckContext(context);
            ChecksPublisher publisher = getPublisher(context);
            if (t instanceof FlowInterruptedException && ((FlowInterruptedException) t).isActualInterruption()) {
                publisher.publish(getDetails(checkContext, ChecksConclusion.CANCELED));
            } else if (publisher.getConclusion(checkContext.getName()) != ChecksConclusion.FAILURE) {
                publisher.publish(getDetails(checkContext, ChecksConclusion.FAILURE));
            }
            context.onFailure(t);
        } catch (Exception e) {
            context.onFailure(e);
        }
    }
}
```

Obviously the API change is sub-optimal, but at least it only affects implementations of this API (of which we have full control :)) rather than consumers of it (which we do not :()

\* it's somewhat scope creep, but I wondered if the ability to update a check should be an implementation detail consumers of the checks api plugin, or something provided by it - e.g. by storing the external id associated with a checks name in this new `ChecksInfo` class. If so, now might be the ideal time to do that.

2020-11-29 15:58 UTC, XiongKezhi commented
Instead of storing the published checks locally, have you ever thought about query them from GitHub? Maybe use the commit: https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#list-check-runs-for-a-git-reference.

This needs extra requests to GitHub, but seems not a not big deal?

2020-11-29 16:09 UTC, mrginglymus commented
Yeah, I think that would be neater for the most part - means that we're not attempting to mirror github's state and hoping we've got it right...

We would still need to add a new API to the publisher though, possibly, for `onSuccess` and `onFailure` to get the current state of the check; so if we add an

```java
    abstract public ChecksConclusion getConclusion(String checksName)
```
to `ChecksPublisher` then implementations can either attempt to store that information locally, or fetch it from the external source.

2020-11-29 16:13 UTC, mrginglymus commented
Though the comment

> Note: The Checks API only looks for pushes in the repository where the check suite or check run were created. Pushes to a branch in a forked repository are not detected and return an empty pull_requests array.

doesn't inspire me with confidence...

2020-11-29 16:29 UTC, XiongKezhi commented
> We would still need to add a new API to the publisher though, possibly, for onSuccess and onFailure to get the current state of the check;

But if we store the info of the check as an invisible action to the run, couldn't we directly resolve it in `StepContext`? 

> doesn't inspire me with confidence...

Yeah, seems a problem; I'll test it.

2020-11-29 17:21 UTC, timja commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +    public WithChecksStep(final String name) {
yes it can take more than one, normally you would use a databoundsetter for any optional parameters

Then the syntax would be:

```
withChecks('Tests') {
...
}
```

```
withChecks(name: 'Tests', myotherparam: 'hello') {
...
}
```

if there's only one mandatory field in constructor then you can omit the parameter name

2020-11-30 08:38 UTC, XiongKezhi commented
@mrginglymus I test and it actually lists check runs of the PR from a forked repo: https://github.com/XiongKezhi/codingstyle/pull/13.
![截屏2020-11-30 下午4 28 52](https://user-images.githubusercontent.com/30348893/100585816-24435400-3329-11eb-92e1-caefa0111817.png)

I think the reason may be: the commits of a PR (filed from a forked repo or not) in the repository tracked by Jenkins are indeed the "pushes in the repository where the check suite or check run were created" as the GitHub doc mentions.

Do you have time to double-check it? Maybe in your repos.

2020-12-01 08:52 UTC, mrginglymus commented
> I think the reason may be: the commits of a PR (filed from a forked repo or not) in the repository tracked by Jenkins are indeed the "pushes in the repository where the check suite or check run were created" as the GitHub doc mentions.

That does make sense (otherwise how would you _create_ check runs) - but then I wonder what the note is about...

2020-12-01 09:14 UTC, mrginglymus commented
So as I see it there are two problems, each with the same two options:

1. Tracking the 'id' of an check so we can update it
  a. we could do this in the checks-api by storing a mapping of `String name: long id`
  b. we could defer this to the implementation, which could either do its own tracking of the id as in a., or it could look up the id on demand
2. Tracking the status of a check so we know whether or not it has been completed at the end of the `withChecks` block
  a. we could do this in the checks-api by storing a mapping of `String name: ChecksConclusion conclusion`
  b. we could defer this to the implementation, which could either do its own tracking of the status as in a., or it could look up the conclusion on demand

For 1., I think b. (doing it within the implementation) seems like it might make more sense as it allows each implementation to have its own understanding of what 'updating' actually means, and minimises api changes for `checks-api` - you just continue to call `publish` and it's up to the implementation to work out if that means an update or a create.

For 2., I think b. also might make sense, again in the interest of minimising changes to the API of the `checks-api` - just adding a `getConclusion(String name)` to the `ChecksPublisher` interface would allow us to implement everything necessary here. We can then decide later on whether we want to track the id/conclusions in `InvisibleAction`s or by fetching on demand, without having to change all the APIs.

I might throw up a quick PR for `github-checks-api` just to put into code the above waffle, as I think it'll make more sense :D

2020-12-14 16:50 UTC, XiongKezhi commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +    public WithChecksStep(final String name) {
So should we make all params optional in case that in the future, some users may only want to inject a certain field like conclusion instead of name?

2020-12-14 17:09 UTC, XiongKezhi commented
cc @mrginglymus (cannot request your review directly in the reviewers, maybe because you are not in the jenkins org)

2020-12-15 13:37 UTC, uhafner requested changes
LGTM, just the pom suppressions should be removed.

2020-12-15 14:07 UTC, timja commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +    public WithChecksStep(final String name) {
if we do that then the user will have to specify the name in a more verbose way,

`withChecks(name: 'hello')` rather than `withChecks('hello')`

2020-12-15 14:09 UTC, timja approved these changes
looks good except for suppression on version

2020-12-15 14:10 UTC, timja requested changes
Hmm are we missing some documentation for this feature?

2020-12-16 06:41 UTC, XiongKezhi commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +    public WithChecksStep(final String name) {
Specify the name wouldn't be annoying for users IMO but make it mandatory will be an issue for future changes?

@mrginglymus What do you think? Do you think there will be situations where you do not want to specify the name but the status (e.g. publish several checks in the same status (say in progress) but with different names in the closure)?

2020-12-16 08:53 UTC, XiongKezhi commented
Snippet Generator Preview:

![截屏2020-12-16 下午4 53 34](https://user-images.githubusercontent.com/30348893/102326321-3e369500-3fbf-11eb-95af-fc09fcc401db.png)

2020-12-16 09:05 UTC, timja commented on README.md
> +- withChecks: you can inject the check's name into the closure for other steps to use:
Developer docs too on how to integrate with this?

2020-12-16 09:47 UTC, mrginglymus commented
Hooray!

This is great, and will hopefully make it a lot easier to have all the plugins have overridable checks names without complicated configuration options on each.

Should we add support for `withChecks` to `publishChecks`? As mentioned in other comments, I'm hoping to have things like:

```groovy
withChecks('Python Tests') {
    publishChecks status: IN_PROGRESS
    try {
        sh 'pytest tests'
        junit 'results.xml'
    } catch (FlowInterruptedException err) {
        publishChecks status: CANCELLED
        throw err
   } catch( Exception err) {
       publishChecks status: FAILED
       throw err
   }
}
```

It would also help serve as a guide to developers on how to use it.

Do you think that the above pattern might be something we could build into the `withChecks` step? AFICT it should be doable by implementing a `BodyExecutionCallback` listener, though I appreciate that perhaps it's too much heavy lifting for a single command. Maybe as a further extension in a separate PR?

2020-12-16 09:59 UTC, timja commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +
Remove this, it's not needed you have the constructor
```suggestion
```

2020-12-16 11:25 UTC, XiongKezhi commented
> Should we add support for withChecks to publishChecks?

I think we should.

> Do you think that the above pattern might be something we could build into the withChecks step? Maybe as a further extension in a separate PR?

I think we should do that and it's ok to do it in this PR?  @timja

And if we do that, we will set the name as a mandatory field, or we don't know what to publish when the exceptions occur.
So for double check, Do you think there will be situations where you do not want to specify the name but only the status (e.g. publish several checks in the same status (say in progress) but with different names in the closure)?

2020-12-16 11:28 UTC, timja commented
> > Should we add support for withChecks to publishChecks?
> 
> I think we should.
> 
> > Do you think that the above pattern might be something we could build into the withChecks step? Maybe as a further extension in a separate PR?
> 
> I think we should do that and it's ok to do it in this PR? @timja
> 

Yes sounds good


> And if we do that, we will set the name as a mandatory field, or we don't know what to publish when the exceptions occur.
> So for double check, Do you think there will be situations where you do not want to specify the name but only the status (e.g. publish several checks in the same status (say in progress) but with different names in the closure)?

If you want different names then use a different closure

2020-12-16 11:36 UTC, mrginglymus commented
What is the expected behaviour if you nest `withChecks` calls? Presumably it's something we don't support (and should explicitly 💥 on)?

2020-12-16 22:52 UTC, uhafner commented on pom.xml
> +    <revision>1.2.0</revision>
It still should be a SNAPSHOT?

2020-12-16 22:53 UTC, uhafner approved these changes

2020-12-17 02:26 UTC, XiongKezhi commented on pom.xml
> +    <revision>1.2.0</revision>
The sem-ver plugin will warn about compatibility if add SNAPSHOT

2020-12-17 08:59 UTC, XiongKezhi commented
Seems the injected `ChecksInfo` cannot be accessed inside the callback? @timja @mrginglymus 

`context.get(ChecksInfo.class)` returns nothing.

2020-12-17 09:15 UTC, timja commented
Not sure

2020-12-17 10:21 UTC, timja commented on pom.xml
> +      <version>2.3.3</version>
this is in the bom
```suggestion
```

2020-12-17 10:21 UTC, timja commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +    public WithChecksStep(final String name) {
I think it should be fine to be mandatory

2020-12-17 10:21 UTC, timja commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                SYSTEM_LOGGER.log(Level.WARNING, "Failed getting TaskListener from the context: " + e);
should we continue at this point or just throw an exception?

2020-12-17 10:21 UTC, timja commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                                .withSummary("occurred while executing withChecks step.")
probably not the concern of with checks? shouldn't this be handled in the step that's in the body?

2020-12-17 10:27 UTC, XiongKezhi commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                context.onSuccess(result);
With the support of the callback, this step may be much more useful (but I'm not sure if that goes beyond this step's scope) than just injecting the properties: it can be used as a progress reporter for the steps in Its closure.

Then, here is an issue:

1. We cannot publish checks on success since we definitely don't want a simple success report check to overwrite what's inside the block (in the context of this API, we don't know about checks updating even if we support that in implementation).

2. If we don't publish success, however, a simple closure in which no step publishes checks using the injected name will leave the check uncompleted forever. (as said before, if the progress reporter feature goes beyond the scope, then this should the users' problem)

2020-12-17 10:34 UTC, XiongKezhi commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                                .withSummary("occurred while executing withChecks step.")
I think we report on failure is ok? Since steps cannot handle mistakes like grammar or step not found, and if that's the case and we do not report on such failures, the checks are left unfinished.

2020-12-17 10:38 UTC, XiongKezhi commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                SYSTEM_LOGGER.log(Level.WARNING, "Failed getting TaskListener from the context: " + e);
That's why I introduced the system_logger, I thought the task listener is ok to miss here since it will not affect the purpose of this step

2020-12-17 10:40 UTC, timja commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                context.onSuccess(result);
> If we don't publish success, however, a simple closure in which no step publishes checks using the injected name will leave the check uncompleted forever. (as said before, if the progress reporter feature goes beyond the scope, then this should the users' problem)

not our problem I think

2020-12-17 13:13 UTC, mrginglymus commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                context.onSuccess(result);
I think it's reasonable to expect users to be responsible for sending a success message (or indeed a failure message) within their invocation of `withChecks`. I did wonder about adding to the publisher API the ability to get the current conclusion (https://github.com/jenkinsci/github-checks-plugin/pull/87/files#diff-9c475e3093c11ae9324debf6c824b9c15277a027428e5c7ed60ad6ac2ac25284R131-R134) so that we could query that in onSuccess and send a generic 'success' check if nothing else was set.

2020-12-19 08:31 UTC, timja commented on docs/consumers-guide.md
> +Currently, the `ChecksInfo` object only includes a `name` specified by users.
```suggestion
Currently, the `ChecksInfo` object only includes a `name` specified by users, it is recommended that you look for this name and set it over your default checks name.

With:
```groovy
withChecks('MyCheck') {
  junit '*.xml'
}
```

The check name is used should be 'MyCheck' instead of the default name.

```

2020-12-19 08:34 UTC, timja approved these changes

2020-12-19 08:34 UTC, timja commented on README.md
> +
must've had this outside the suggestion fence before
```suggestion

The check name that is used should be 'MyCheck' instead of the default name.

```

2020-12-19 08:35 UTC, timja commented on README.md
> +
hmm is fine I think

2020-12-19 08:36 UTC, XiongKezhi commented on src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
> +                context.onSuccess(result);
That seems not feasible, since in the context of the API, we don't expect the implementation to possess the `ChecksDetails` alone the build, and if we take that as a users' responsible, there is no need to add the `getConclusion` method only for this feature IMO.

2020-12-20 06:25 UTC, merged